import { useState } from 'react'
import { useBuilderStore } from '../../store/builderStore'
import { generateHTML } from '../../generator/htmlGenerator'
import { generateReact } from '../../generator/reactGenerator'
import { cn } from '../../utils/cn'
import { Copy, Check } from 'lucide-react'

/**
 * CodePanel
 * Shows generated HTML or React code for the current canvas.
 */
export function CodePanel() {
  const canvas = useBuilderStore((s) => s.project.canvas)
  const codeTab = useBuilderStore((s) => s.codeTab)
  const setCodeTab = useBuilderStore((s) => s.setCodeTab)
  const [copied, setCopied] = useState(false)

  const code = codeTab === 'html' ? generateHTML(canvas) : generateReact(canvas)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="flex-1 flex flex-col bg-[#1D1D1F] overflow-hidden animate-fade-in">
      {/* Tab bar */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-white/10">
        <div className="flex items-center gap-1">
          {(['html', 'react'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setCodeTab(tab)}
              className={cn(
                'px-3 py-1.5 rounded-md text-sm font-medium transition-all duration-150',
                codeTab === tab
                  ? 'bg-white/10 text-white'
                  : 'text-white/50 hover:text-white/80',
              )}
            >
              {tab === 'html' ? 'HTML + Tailwind' : 'React (JSX)'}
            </button>
          ))}
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium bg-white/10 text-white hover:bg-white/20 transition-all duration-150"
        >
          {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>

      {/* Code area */}
      <div className="flex-1 overflow-auto p-4">
        <pre className="text-sm font-mono text-white/90 leading-relaxed whitespace-pre-wrap break-words">
          <code>{code}</code>
        </pre>
      </div>

      {/* Footer */}
      <div className="px-4 py-2 border-t border-white/10 flex items-center justify-between">
        <p className="text-xs text-white/40">
          {canvas.length} component{canvas.length !== 1 ? 's' : ''} · Generated by MikeUI
        </p>
        <p className="text-xs text-white/40 font-mono">
          {code.split('\n').length} lines
        </p>
      </div>
    </div>
  )
}
